### PR TITLE
Added support for converting functions used as part of default constraints.

### PR DESCRIPTION
**Pull request by JCallico**
Added support for converting functions used as part of default constraints:
- user_name to CURRENT_USER.
- datepart to date_part and wrapping date part type in single quotes.
- Brakets to double quotes.

Also made regex matching case insensitive.

### CODE REVIEW

**Comment by marco44** [comment]
Hi,

I feel that this regexp "$code =~ s/datepart\s*\(\s*(.*)\s*\,\s*(.*)\s*\)/date_part('$1', $2)/gi;" is a bit fragile.

I'd reduce the greediness of the .* to avoid grabbing some spaces…

$code =~ s/datepart\s*\(\s*(.*?)\s*\,\s*(.*?)\s*\)/date_part('$1', $2)/gi;

feels more secure.

**Comment by marco44** [comment]
Oh, I forgot to say thanks :)

Tell me if you want me to do the correction or if you'd rather do it yourself…

**Comment by JCallico** [comment]
You are most welcome.

I tried using the new expression and it didn't work for me.

This is the constraint as it was generated by the SSMS:

`ALTER TABLE [dbo].[xxx] ADD  CONSTRAINT [DF_x_Year]  DEFAULT (datepart(year,getdate())) FOR [Year]`

Try for yourself, please.

**Comment by JCallico** [comment]
Also, a question: If you are able to convert MSSQL functions successfully why not add the resulting constraint to the after script as its currently doing with the null constraints?

Something like this: 

```
			my $code=convert_transactsql_code($value);
            $objects->{SCHEMAS}->{$schema}->{TABLES}->{$table}->{COLS}->{$col}->{DEFAULT}->{VALUE}
                = $code;
            $objects->{SCHEMAS}->{$schema}->{TABLES}->{$table}->{COLS}->{$col}->{DEFAULT}->{UNSURE}
                = $value != $code ? 1 : 0;
```

**Comment by marco44** [comment]
It seems it's this box that corrupted what I typed : your original regexp was also damaged. I had to display it as code… this should work:

`s/datepart\s*\(\s*(.*?)\s*\,\s*(.*?)\s*\)/date_part('$1', $2)/gi;`

The * were interpreted by markdown…

**Comment by marco44** [comment]
For the other question: I can never be sure that everything that is in the function has been correctly converted. There are a lot of functions that aren't caught by this tool (and there are some more at each new SQL Server version :) )

**Comment by JCallico** [comment]
Agree, the new expression making the matching expression less greedy is much more secure.

**Comment by JCallico** [comment]
It's not a big deal either way but my point was that if the regex transforms the original SQL code then we must be sure that the conversion was right or then there is a problem in the regex itself.

If the original SQL code is not transformed and doesn't change then you keep adding it to the unsure, that's why I recommended the ternary assignment:

```
$objects->{SCHEMAS}->{$schema}->{TABLES}->{$table}->{COLS}->{$col}->{DEFAULT}->{UNSURE}
                = $value != $code ? 1 : 0;
```

**Comment by marco44** [comment]
Ok, I get it. But if the original SQL code is not transformed, it could still be unsure. For instance if there is a function we don't know how to convert.

**Comment by JCallico** [comment]
Exactly, that's why I propose comparing the value returned from the conversion function with the original value. As I said before It's not a big deal.

**Comment by marco44** [comment]
Sorry, maybe I don't get it, but why having an identical value before and after the conversion function would make the value not unsure ?

**Comment by JCallico** [comment]
Currently all default constraints using functions are set to unsure. My point is that if the original value is modified is because one of the conversion rules, which we are "sure" of, kicked in otherwise the constraint remains "unsure" since we can't tell if it will work or not.

I'm just trying to make the list of things of "unsure" statements shorter.

**Comment by JCallico** [comment]
ahhhh I see your confusion, my sample code must be swapped:

`$value != $code ? 0 : 1;`

different = sure
equal = unsure

**Comment by marco44** [comment]
That was one part. But there is more though :)

Well, we are sure of the conversion rules. But we cannot be sure that only those conversion rules apply …

Lets say your constraint isn't `ALTER TABLE [dbo].[xxx] ADD CONSTRAINT [DF_x_Year] DEFAULT (datepart(year,getdate())) FOR [Year]`

but

`ALTER TABLE [dbo].[xxx] ADD CONSTRAINT [DF_x_Year] DEFAULT (my_sqlserver_fancyfunction(datepart(year,getdate())), myfancyfunctionparameter) FOR [Year]`

This rule would match the regexp. The result would still be unsure though. And there are a lot of fancy cases like this. That's why we cannot be sure.

Maybe if I had written a full parser for this, such as a BNF parser, I could guarantee that there were only known constructions in the expression. With regexps I cannot (or at least, not easily).

**Comment by JCallico** [comment]
I see, it totally makes sense.

**Comment by marco44** [comment]
Thanks a lot !

**Pull request merged**
