### PR TITLE
#107 parse view query

### PR DESCRIPTION
**Pull request by madtibo**
Parse the query used to build the views.

In case strings are aggregated using the '+' operator, change it to the PG operator '||'.

### CODE REVIEW

**Comment by alchemistmatt** [comment]
This is a great addition, and I have incorporated it into my fork at https://github.com/PNNL-Comp-Mass-Spec/sqlserver2pgsql/tree/Parse_view_query
I am, however, confused by your RegEx 
`/^\s*\(([^\)]+)\)\s*AS\s+SELECT\s+(.*)\s+FROM\s+(.*)$/i`

This implies a CREATE VIEW syntax where the view's columns are specified before the `AS` keyword.  In my experience, the CREATE VIEW DDL looks something like this
```sql
CREATE VIEW [dbo].[V_Residues]
AS
SELECT Residue_ID,
       Residue_Symbol,
       Description,
       Average_Mass,
       Monoisotopic_Mass
FROM dbo.T_Residues
```

For this syntax, a better RegEx is `m/^\s*AS\s+SELECT\s+(.*)\s+FROM\s+(.*)$/is`, as shown via this commit:
https://github.com/PNNL-Comp-Mass-Spec/sqlserver2pgsql/commit/ded6aaeff7aedd3f7175c187f37119f09caa938d#diff-ff9cf9f586c7267becfbc8f858a7fd87R1751

Note also the use of `/is` to indicate that `.` should match a newline.

**Comment by madtibo** [comment]
> This is a great addition, and I have incorporated it into my fork at https://github.com/PNNL-Comp-Mass-Spec/sqlserver2pgsql/tree/Parse_view_query

Cool :-)

> I am, however, confused by your RegEx
> `/^\s*\(([^\)]+)\)\s*AS\s+SELECT\s+(.*)\s+FROM\s+(.*)$/i`
> 
> This implies a CREATE VIEW syntax where the view's columns are specified before the `AS` keyword. In my experience, the CREATE VIEW DDL looks something like this
> 
> ```sql
> CREATE VIEW [dbo].[V_Residues]
> AS
> SELECT Residue_ID,
>        Residue_Symbol,
>        Description,
>        Average_Mass,
>        Monoisotopic_Mass
> FROM dbo.T_Residues
> ```
> 
> For this syntax, a better RegEx is `m/^\s*AS\s+SELECT\s+(.*)\s+FROM\s+(.*)$/is`, as shown via this commit:
> [PNNL-Comp-Mass-Spec@ded6aae#diff-ff9cf9f586c7267becfbc8f858a7fd87R1751](https://github.com/PNNL-Comp-Mass-Spec/sqlserver2pgsql/commit/ded6aaeff7aedd3f7175c187f37119f09caa938d#diff-ff9cf9f586c7267becfbc8f858a7fd87R1751)
> 
> Note also the use of `/is` to indicate that `.` should match a newline.

We should find a way to parse both cases. What about:
```
m/^\s*\(([^\)]+)\)\s*AS\s+SELECT\s+(.*)\s+FROM\s+(.*)$/is
```

**Comment by madtibo** [comment]
Common migration issues:

* [Most common errors - endpoint](https://www.endpoint.com/blog/2019/01/23/migrate-from-sql-server-to-postgresql)
* [Incompatibilities - severalnines](https://severalnines.com/database-blog/migrating-mssql-postgresql-what-you-should-know)

**Comment by madtibo** [comment]
regex upgrade done in #152

**Pull request closed without merging**
