### PR TITLE
parse index included columns (available for PG 11 onward)

### PR DESCRIPTION
**Pull request by madtibo**

### CODE REVIEW

**Comment by madtibo** [comment]
#131

**Comment by mikes-gh** [comment]
Using your branch CREATE index is no longer outputted  to after.sql.
Using master the index is outputted without INCLUDE as expected

**Comment by mikes-gh** [comment]
https://github.com/dalibo/sqlserver2pgsql/blob/40555b9f98ce32abb63973163c13614356a74fc9/sqlserver2pgsql.pl#L2684
I thino you're not outputing INCLUDE indexes to after.sql

**Comment by madtibo** [comment]
You are right. Since I am treating it with the WHERE clause, I am outputting it to unsure.  
I will look into it to make it to the after.sql file.

**Comment by madtibo** [comment]
@mikes-gh is it better with this new version?

**Comment by mikes-gh** [comment]
All working well resulting `after.sql` script contains
```sql
CREATE INDEX "ix_transactions_transdate" ON "public"."transactions" ("transdate" ASC) INCLUDE ("accountno","netvalue");
```
and resulting index in postgres looks correct
```sql
CREATE INDEX ix_transactions_transdate
    ON public.transactions USING btree
    (transdate ASC NULLS LAST)
    INCLUDE(accountno, netvalue)
    TABLESPACE pg_default;
```
Thanks a lot for this 👍

**Pull request merged**
